spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/simple-auth-app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.thymeleaf.cache=false

# アプリ起動時に毎回schema.sqlを実行
spring.sql.init.mode=always

# HTTPS化
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
