spring.application.name=app

spring.datasource.url=jdbc:postgresql://localhost:5432/simple-auth-app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.thymeleaf.cache=false
